engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
      Identical code:
        enabled: false
    config:
      languages:
        - javascript
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
      errors:
        enabled: false
      universal-selector:
        enabled: false
ratings:
  paths:
  - "**.js"
  - "**.css"
exclude_paths:
  - db/
  - loadtest/
  - /node_modules/
  - /client/build/
  - scripts/lib/
  - webpack.config.js
  - test/
  - CHANGELOG.md
  - LICENSE
  - README.md
  - client/apidocs.html
  - client/images/
  - /doc/
  - /views/
  - client/styles/fonts/
  - nightwatch.json
  - package.json
